uio() API
[Synesis Software UNIX Emulation for Win32]
Detailed Description
UIO functions and types.
Classes
struct iovec
Defines a memory vector.
Typedefs
typedef signed long ssize_t
Signed size type.
Functions
ssize_t readv (int fd, struct iovec const *vector, int count)
Reads from a file into a set of memory blocks.
ssize_t writev (int fd, struct iovec const *vector, int count)
Writes to a file from a set of memory blocks.
Typedef Documentation
typedef signed long ssize_t
Signed size type.
Function Documentation
ssize_t readv (int fd, struct iovec const * vector, int count)
Reads from a file into a set of memory blocks.
Parameters:
fd The file from which to read
vector pointer to the first element in the vector
count the number of elements in the vector
References errno_from_Win32(), iovec::iov_len, and unixem_Windows_HANDLE_from_file_handle().
ssize_t writev (int fd, struct iovec const * vector, int count)
Writes to a file from a set of memory blocks.
Parameters:
fd The file to which to write
vector pointer to the first element in the vector
count the number of elements in the vector
References errno_from_Win32(), iovec::iov_base, iovec::iov_len, and unixem_Windows_HANDLE_from_file_handle().
UNIX Emulation for Win32 Libraries documentation © Synesis Software Pty Ltd, 2002-2010